name: 'Itly Branch'
description: 'Verify the Iteratively branch'
inputs:
  expected-branch:
    description: 'Branch to expect in .itlyrc'
    required: true
    default: 'main'
outputs:
  detected-branch:
    description: 'The branch present in .itlyrc'
runs:
  using: 'node12'
  main: 'dist/index.js'
